---

image: alpine:latest

stages:
  - lint
  - build
  - release

lint:
  stage: lint
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - apk add --no-cache bash findutils
    # yamllint disable-line rule:line-length
    - 'wget --header="JOB-TOKEN: $CI_JOB_TOKEN" ${CI_API_V4_URL}/projects/oarmstrong%2Folint/packages/generic/olint/1.0.0/olint'
    - bash olint

build:
  stage: build
  image: gcc:10
  artifacts:
    paths:
      - build/ralt2hyper
  script:
    - apt-get --yes update
    - apt-get --yes install cmake
    - cmake -B build -DCMAKE_BUILD_TYPE=Release
    - make -C build
